export const provincesTH = [
  'สตูล',
  'ระยอง',
  'ชุมพร',
  'มหาสารคาม',
  'สุราษฎร์ธานี',
  'ชลบุรี',
  'ตรัง',
  'จันทบุรี',
  'พังงา',
  'ตราด',
  'ระนอง',
  'ภูเก็ต',
  'กระบี่',
  'กรุงเทพมหานคร',
  'นครศรีธรรมราช',
  'สมุทรสาคร',
  'พระนครศรีอยุธยา',
  'ลพบุรี',
  'สมุทรปราการ',
  'อ่างทอง',
  'ปัตตานี',
  'เชียงใหม่',
  'ชัยนาท',
  'นนทบุรี',
  'อุตรดิตถ์',
  'ขอนแก่น',
  'นครสวรรค์',
  'เพชรบุรี',
  'สิงห์บุรี',
  'สมุทรสงคราม',
  'ราชบุรี',
  'นครนายก',
  'สระบุรี',
  'นครปฐม',
  'กาญจนบุรี',
  'ปทุมธานี',
  'พิษณุโลก',
  'ฉะเชิงเทรา',
  'เชียงราย',
  'สงขลา',
  'ลำพูน',
  'หนองคาย',
  'อุบลราชธานี',
  'สุโขทัย',
  'พะเยา',
  'อุทัยธานี',
  'แพร่',
  'เพชรบูรณ์',
  'แม่ฮ่องสอน',
  'บุรีรัมย์',
  'พิจิตร',
  'น่าน',
  'ยะลา',
  'สุพรรณบุรี',
  'นครราชสีมา',
  'ปราจีนบุรี',
  'ตาก',
  'ร้อยเอ็ด',
  'นครพนม',
  'มุกดาหาร',
  'สระแก้ว',
  'อุดรธานี',
  'ลำปาง',
  'ศรีสะเกษ',
  'ยโสธร',
  'พัทลุง',
  'นราธิวาส',
  'เลย',
  'กาฬสินธุ์',
  'สุรินทร์',
  'ประจวบคีรีขันธ์',
  'ชัยภูมิ',
  'สกลนคร',
  'กำแพงเพชร',
  'อำนาจเจริญ',
  'หนองบัวลำภู',
  'บึงกาฬ'
]

export const provincesEN = [
  'Satun',
  'Rayong',
  'Chumphon',
  'Maha Sarakham',
  'Surat Thani',
  'Chon Buri',
  'Trang',
  'Chanthaburi',
  'Phang-nga',
  'Trat',
  'Ranong',
  'Phuket',
  'Krabi',
  'Bangkok',
  'Nakhon Si Thammarat',
  'Samut Sakhon',
  'Phra Nakhon Si Ayutthaya',
  'Lop Buri',
  'Samut Prakarn',
  'Ang Thong',
  'Pattani',
  'Chiang Mai',
  'Chai Nat',
  'Nonthaburi',
  'Uttaradit',
  'Khon Kaen',
  'Nakhon Sawan',
  'Phetchaburi',
  'Sing Buri',
  'Samut Songkhram',
  'Ratchaburi',
  'Nakhon Nayok',
  'Saraburi',
  'Nakhon Pathom',
  'Kanchanaburi',
  'Pathum Thani',
  'Phitsanulok',
  'Chachoengsao',
  'Chiang Rai',
  'Songkhla',
  'Lamphun',
  'Nong Khai',
  'Ubon Ratchathani',
  'Sukhothai',
  'Phayao',
  'Uthai Thani',
  'Phrae',
  'Phetchabun',
  'Mae Hong Son',
  'Buri Ram',
  'Phichit',
  'Nan',
  'Yala',
  'Suphan Buri',
  'Nakhon Ratchasima',
  'Prachin Buri',
  'Tak',
  'Roi Et',
  'Nakhon Phanom',
  'Mukdahan',
  'Sa kaeo',
  'Udon Thani',
  'Lampang',
  'Si Sa Ket',
  'Yasothon',
  'Phatthalung',
  'Narathiwat',
  'Loei',
  'Kalasin',
  'Surin',
  'Prachuap Khiri Khan',
  'Chaiyaphum',
  'Sakon Nakhon',
  'Kamphaeng Phet',
  'Amnat Charoen',
  'Nong Bua Lam Phu',
  'Bueng Kan'
]
